'use strict';

module.exports = {
  apps: [
    {
      name: 'adisyum-website',
      cwd: './apps/website',
      script: 'node',
      args: '.next/standalone/server.js',
      exec_mode: 'cluster',
      instances: 2,
      env_production: {
        NODE_ENV: 'production',
        PORT: 3010,
        HOSTNAME: '0.0.0.0',
      },
      error_file: './logs/website-error.log',
      out_file: './logs/website-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'adisyum-pos-app',
      cwd: '.',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      exec_mode: 'cluster',
      instances: 'max',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/pos-error.log',
      out_file: './logs/pos-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
      autorestart: true,
      watch: false,
    },
    {
      name: 'adisyum-system-admin',
      cwd: '.',
      script: 'node_modules/.bin/next',
      args: 'start -p 3020',
      exec_mode: 'cluster',
      instances: 1,
      env_production: {
        NODE_ENV: 'production',
        PORT: 3020,
      },
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
  ],
};
