#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="${APP_DIR:-/root/adisyum}"
APP_USER="${APP_USER:-root}"
DOMAIN="${DOMAIN:-adisyum.com}"
ROOT_PORT="${ROOT_PORT:-3000}"
WEBSITE_PORT="${WEBSITE_PORT:-3010}"
ROOT_ASSET_PREFIX="${ROOT_ASSET_PREFIX:-/adisyum-root-assets}"
SSL_CERT="${SSL_CERT:-/etc/ssl/cloudflare/origin.pem}"
SSL_KEY="${SSL_KEY:-/etc/ssl/cloudflare/origin.key}"
BACKUP_ROOT="${BACKUP_ROOT:-/var/backups/adisyum-clean-reconstruct}"
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_ROOT}/${TS}"
LOG_DIR="${APP_DIR}/deploy/logs"
LOG_FILE="${LOG_DIR}/reconstruct-vps-runtime-${TS}.log"

mkdir -p "${LOG_DIR}" "${BACKUP_DIR}"
exec > >(tee -a "${LOG_FILE}") 2>&1

log() {
  printf '[%s] %s\n' "$(date -Is)" "$*"
}

fail() {
  log "ERROR: $*"
  log "Backup: ${BACKUP_DIR}"
  log "Log: ${LOG_FILE}"
  exit 1
}

run() {
  log "RUN: $*"
  "$@"
}

run_app() {
  if [[ "$(id -un)" == "${APP_USER}" ]]; then
    run "$@"
  else
    run sudo -E -H -u "${APP_USER}" "$@"
  fi
}

require_root() {
  [[ "${EUID}" -eq 0 ]] || fail "Run as root: sudo APP_DIR=${APP_DIR} APP_USER=${APP_USER} bash deploy/scripts/reconstruct-vps-runtime.sh"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

require_layout() {
  [[ -d "${APP_DIR}" ]] || fail "APP_DIR not found: ${APP_DIR}"
  [[ -f "${APP_DIR}/package.json" ]] || fail "Root package.json missing."
  [[ -f "${APP_DIR}/ecosystem.config.cjs" ]] || fail "ecosystem.config.cjs missing."
  [[ -d "${APP_DIR}/apps/website" ]] || fail "apps/website missing."
  [[ -f "${APP_DIR}/prisma/schema.prisma" ]] || fail "prisma/schema.prisma missing."
  [[ -s "${SSL_CERT}" ]] || fail "SSL certificate missing: ${SSL_CERT}"
  [[ -s "${SSL_KEY}" ]] || fail "SSL key missing: ${SSL_KEY}"
}

generate_secret() {
  openssl rand -base64 48 | tr -d '\n'
}

write_env_line() {
  local name="$1"
  local value="$2"
  printf '%s=%q\n' "${name}" "${value}"
}

recover_or_create_env() {
  cd "${APP_DIR}"

  if [[ -f ".env.production" ]]; then
    chmod 600 ".env.production" || true
    log "Using existing ${APP_DIR}/.env.production"
    return 0
  fi

  if [[ -f ".env" ]]; then
    cp -a ".env" ".env.production"
    chmod 600 ".env.production" || true
    log "Recovered .env.production from ${APP_DIR}/.env"
    return 0
  fi

  if [[ -f ".env.local" ]]; then
    cp -a ".env.local" ".env.production"
    chmod 600 ".env.production" || true
    log "Recovered .env.production from ${APP_DIR}/.env.local"
    return 0
  fi

  local recovered=""
  recovered="$(
    find /var/backups /root -maxdepth 7 -type f \( -name '.env.production' -o -name '.env' -o -name '.env.local' \) 2>/dev/null \
      | grep -v "^${APP_DIR}/" \
      | sort -r \
      | head -n 1 || true
  )"

  if [[ -n "${recovered}" && -s "${recovered}" ]]; then
    cp -a "${recovered}" ".env.production"
    chmod 600 ".env.production" || true
    log "Recovered .env.production from backup/env candidate: ${recovered}"
    return 0
  fi

  log "No existing env file found; creating ${APP_DIR}/.env.production with generated secrets and explicit required runtime fields"
  local generated_secret generated_admin generated_gib
  generated_secret="$(generate_secret)"
  generated_admin="$(generate_secret)"
  generated_gib="$(generate_secret)"

  {
    echo "# Generated by deploy/scripts/reconstruct-vps-runtime.sh on $(date -Is)"
    echo "# DATABASE_URL and Redis values cannot be invented safely; set them to the real production values."
    write_env_line NODE_ENV "production"
    write_env_line APP_ENV "production"
    write_env_line NEXT_PUBLIC_APP_URL "https://${DOMAIN}"
    write_env_line ADISYUM_ROOT_ASSET_PREFIX "${ROOT_ASSET_PREFIX}"
    write_env_line DATABASE_URL "${DATABASE_URL:-}"
    write_env_line POSTGRES_POOL_MAX "${POSTGRES_POOL_MAX:-10}"
    write_env_line POSTGRES_IDLE_TIMEOUT_MS "${POSTGRES_IDLE_TIMEOUT_MS:-30000}"
    write_env_line POSTGRES_CONNECT_TIMEOUT_MS "${POSTGRES_CONNECT_TIMEOUT_MS:-10000}"
    write_env_line SLOW_QUERY_THRESHOLD_MS "${SLOW_QUERY_THRESHOLD_MS:-300}"
    write_env_line ADISYUM_JWT_SECRET "${ADISYUM_JWT_SECRET:-${NEXTAUTH_SECRET:-${generated_secret}}}"
    write_env_line NEXTAUTH_SECRET "${NEXTAUTH_SECRET:-${ADISYUM_JWT_SECRET:-${generated_secret}}}"
    write_env_line ADISYUM_SUPER_ADMIN_PASSWORD "${ADISYUM_SUPER_ADMIN_PASSWORD:-${BOOTSTRAP_ADMIN_PASSWORD:-1234}}"
    write_env_line BOOTSTRAP_TENANT_ID "${BOOTSTRAP_TENANT_ID:-ABN-48291}"
    write_env_line BOOTSTRAP_BRANCH_ID "${BOOTSTRAP_BRANCH_ID:-mrk}"
    write_env_line BOOTSTRAP_ADMIN_USERNAME "${BOOTSTRAP_ADMIN_USERNAME:-admin}"
    write_env_line BOOTSTRAP_ADMIN_PASSWORD "${BOOTSTRAP_ADMIN_PASSWORD:-1234}"
    write_env_line UPSTASH_REDIS_REST_URL "${UPSTASH_REDIS_REST_URL:-}"
    write_env_line UPSTASH_REDIS_REST_TOKEN "${UPSTASH_REDIS_REST_TOKEN:-}"
    write_env_line UPLOAD_ROOT_DIR "${UPLOAD_ROOT_DIR:-${APP_DIR}/public/uploads}"
    write_env_line GIB_CREDENTIAL_SECRET "${GIB_CREDENTIAL_SECRET:-${generated_gib}}"
    write_env_line AURELIA_API_URL "${AURELIA_API_URL:-http://127.0.0.1:8000}"
    write_env_line AURELIA_TENANT_KEY "${AURELIA_TENANT_KEY:-default}"
    write_env_line AURELIA_BACKEND_EMAIL "${AURELIA_BACKEND_EMAIL:-admin@aurelia.local}"
    write_env_line AURELIA_BACKEND_PASSWORD "${AURELIA_BACKEND_PASSWORD:-}"
  } > ".env.production"
  chmod 600 ".env.production" || true
}

env_value_is_placeholder() {
  local value="${1:-}"
  [[ -z "${value}" ]] && return 0
  [[ "${value}" == *CHANGE_ME* ]] && return 0
  [[ "${value}" == *"<"*">"* ]] && return 0
  [[ "${value}" == *"example.com"* ]] && return 0
  [[ "${value}" == *'${'* ]] && return 0
  return 1
}

require_env_var() {
  local name="$1"
  local value="${!name:-}"
  if env_value_is_placeholder "${value}"; then
    MISSING_ENV+=("${name}")
  fi
}

require_secret_len() {
  local name="$1"
  local min_len="$2"
  local value="${!name:-}"
  if env_value_is_placeholder "${value}" || (( ${#value} < min_len )); then
    MISSING_ENV+=("${name} (must be at least ${min_len} chars)")
  fi
}

validate_database_url() {
  case "${DATABASE_URL:-}" in
    postgresql://*|postgres://*) ;;
    *) MISSING_ENV+=("DATABASE_URL (must start with postgresql:// or postgres://)") ;;
  esac
}

validate_environment() {
  MISSING_ENV=()

  require_env_var DATABASE_URL
  validate_database_url

  if [[ -z "${ADISYUM_JWT_SECRET:-}" && -n "${NEXTAUTH_SECRET:-}" ]]; then
    export ADISYUM_JWT_SECRET="${NEXTAUTH_SECRET}"
  fi
  if [[ -z "${NEXTAUTH_SECRET:-}" && -n "${ADISYUM_JWT_SECRET:-}" ]]; then
    export NEXTAUTH_SECRET="${ADISYUM_JWT_SECRET}"
  fi
  require_secret_len ADISYUM_JWT_SECRET 32
  require_secret_len NEXTAUTH_SECRET 32

  require_env_var ADISYUM_SUPER_ADMIN_PASSWORD
  require_env_var BOOTSTRAP_TENANT_ID
  require_env_var BOOTSTRAP_BRANCH_ID
  require_env_var BOOTSTRAP_ADMIN_USERNAME
  require_env_var BOOTSTRAP_ADMIN_PASSWORD

  require_env_var UPSTASH_REDIS_REST_URL
  require_env_var UPSTASH_REDIS_REST_TOKEN
  require_secret_len GIB_CREDENTIAL_SECRET 32

  if (( ${#MISSING_ENV[@]} > 0 )); then
    {
      echo "Missing or invalid production environment:"
      printf ' - %s\n' "${MISSING_ENV[@]}"
      echo
      echo "Create ${APP_DIR}/.env.production from ${APP_DIR}/.env.production.example and replace all CHANGE_ME values."
    } >&2
    fail "Production environment validation failed."
  fi

  export NEXTAUTH_SECRET ADISYUM_JWT_SECRET
  export BOOTSTRAP_TENANT_ID BOOTSTRAP_BRANCH_ID BOOTSTRAP_ADMIN_USERNAME BOOTSTRAP_ADMIN_PASSWORD
  export ADISYUM_SUPER_ADMIN_PASSWORD
  export DATABASE_URL UPSTASH_REDIS_REST_URL UPSTASH_REDIS_REST_TOKEN GIB_CREDENTIAL_SECRET
  log "Production environment validation OK."
}

backup_preserved_state() {
  log "Creating reconstruction backup at ${BACKUP_DIR}"
  mkdir -p "${BACKUP_DIR}/project" "${BACKUP_DIR}/nginx" "${BACKUP_DIR}/pm2"

  cp -a "${APP_DIR}/.env" "${BACKUP_DIR}/project/.env" 2>/dev/null || true
  cp -a "${APP_DIR}/.env.production" "${BACKUP_DIR}/project/.env.production" 2>/dev/null || true
  cp -a "${APP_DIR}/.env.local" "${BACKUP_DIR}/project/.env.local" 2>/dev/null || true
  cp -a "${APP_DIR}/public/uploads" "${BACKUP_DIR}/project/uploads" 2>/dev/null || true
  cp -a "${APP_DIR}/uploads" "${BACKUP_DIR}/project/root-uploads" 2>/dev/null || true
  cp -a "${APP_DIR}/ecosystem.config.cjs" "${BACKUP_DIR}/project/ecosystem.config.cjs" 2>/dev/null || true
  cp -a "${APP_DIR}/deploy-production.sh" "${BACKUP_DIR}/project/deploy-production.sh" 2>/dev/null || true

  cp -a /etc/nginx/nginx.conf "${BACKUP_DIR}/nginx/nginx.conf" 2>/dev/null || true
  cp -a /etc/nginx/sites-available "${BACKUP_DIR}/nginx/sites-available" 2>/dev/null || true
  cp -a /etc/nginx/sites-enabled "${BACKUP_DIR}/nginx/sites-enabled" 2>/dev/null || true
  cp -a /etc/nginx/conf.d "${BACKUP_DIR}/nginx/conf.d" 2>/dev/null || true
  nginx -T > "${BACKUP_DIR}/nginx/nginx-T.before.txt" 2>&1 || true

  pm2 save || true
  cp -a "/root/.pm2/dump.pm2" "${BACKUP_DIR}/pm2/dump.pm2" 2>/dev/null || true

  git -C "${APP_DIR}" status --short > "${BACKUP_DIR}/project/git-status.txt" 2>/dev/null || true
  git -C "${APP_DIR}" rev-parse HEAD > "${BACKUP_DIR}/project/git-head.txt" 2>/dev/null || true
}

load_env() {
  cd "${APP_DIR}"
  if [[ -f ".env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source ".env"
    set +a
  fi
  if [[ -f ".env.production" ]]; then
    set -a
    # shellcheck disable=SC1091
    source ".env.production"
    set +a
  fi
  if [[ -f ".env.local" ]]; then
    set -a
    # shellcheck disable=SC1091
    source ".env.local"
    set +a
  fi
  [[ -n "${DATABASE_URL:-}" ]] || fail "DATABASE_URL is required."
  [[ "${DATABASE_URL}" != *'$'* ]] || fail "DATABASE_URL contains unresolved variable syntax."

  export NODE_ENV=production
  export APP_ENV=production
  export ADISYUM_ROOT_ASSET_PREFIX="${ROOT_ASSET_PREFIX}"
  export NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL:-https://${DOMAIN}}"
  export UPLOAD_ROOT_DIR="${UPLOAD_ROOT_DIR:-${APP_DIR}/public/uploads}"
  export ADISYUM_SUPER_ADMIN_PASSWORD="${ADISYUM_SUPER_ADMIN_PASSWORD:-${BOOTSTRAP_ADMIN_PASSWORD:-1234}}"
  export BOOTSTRAP_TENANT_ID="${BOOTSTRAP_TENANT_ID:-ABN-48291}"
  export BOOTSTRAP_BRANCH_ID="${BOOTSTRAP_BRANCH_ID:-mrk}"
  export BOOTSTRAP_ADMIN_USERNAME="${BOOTSTRAP_ADMIN_USERNAME:-admin}"
  export BOOTSTRAP_ADMIN_PASSWORD="${BOOTSTRAP_ADMIN_PASSWORD:-1234}"
  validate_environment
}

inspect_drift_before_cleanup() {
  log "Inspecting drift before cleanup"
  {
    echo "## PM2"
    pm2 list || true
    pm2 jlist || true
    echo
    echo "## Listening ports"
    ss -ltnp || true
    echo
    echo "## NGINX drift"
    nginx -T 2>/dev/null | grep -E "server_name|proxy_pass|location|3020|app\\.${DOMAIN}|admin\\.${DOMAIN}" || true
    echo
    echo "## Build/runtime artifacts"
    find "${APP_DIR}" -maxdepth 4 \( -name ".next" -o -name "standalone" -o -name ".output" -o -name "out" -o -name "node_modules" \) -print || true
  } > "${BACKUP_DIR}/drift-before-cleanup.txt" 2>&1 || true
}

stop_all_runtime() {
  log "Stopping all runtime services managed by PM2"
  pm2 delete all || true
  pm2 kill || true
}

clean_pm2_state() {
  log "Cleaning PM2 daemon, dump, pid, and socket state"
  local app_home
  app_home="$(getent passwd "${APP_USER}" | cut -d: -f6 || true)"
  [[ -n "${app_home}" ]] || app_home="/root"

  rm -f "${app_home}/.pm2/dump.pm2" "${app_home}/.pm2/dump.pm2.bak" "${app_home}/.pm2/module_conf.json" || true
  rm -rf "${app_home}/.pm2/pids" "${app_home}/.pm2/rpc.sock" "${app_home}/.pm2/pub.sock" || true
  rm -rf "/root/.pm2/pids" "/root/.pm2/rpc.sock" "/root/.pm2/pub.sock" || true
}

clean_filesystem_runtime() {
  log "Cleaning runtime/build/dependency artifacts while preserving source, env, DB, and uploads"
  cd "${APP_DIR}"

  rm -rf .next apps/website/.next
  rm -rf .next/standalone apps/website/.next/standalone standalone .output out
  rm -rf node_modules apps/website/node_modules
  rm -rf .turbo .cache .parcel-cache
  rm -f tsconfig.tsbuildinfo apps/website/tsconfig.tsbuildinfo
  rm -f ecosystem.config.js ecosystem.isolated.config.cjs apps/website/ecosystem.config.js
  rm -f deploy/nginx/app.conf deploy/nginx/admin.conf deploy/nginx/website.conf 2>/dev/null || true
}

install_dependencies() {
  log "Installing dependencies deterministically"
  cd "${APP_DIR}"
  if [[ -f package-lock.json ]]; then
    run_app npm ci --include=dev
  else
    run_app npm install --include=dev
  fi

  if [[ -f apps/website/package-lock.json ]]; then
    run_app npm --prefix apps/website ci --include=dev
  else
    run_app npm --prefix apps/website install --include=dev
  fi
}

validate_node_runtime() {
  log "Validating Node runtime and local TypeScript bootstrap runner"
  cd "${APP_DIR}"
  node - <<'NODE'
console.log(`node runtime OK: ${process.versions.node}`);
NODE
  if ! node -e "const [major, minor] = process.versions.node.split('.').map(Number); process.exit(major > 22 || (major === 22 && minor >= 6) ? 0 : 1)"; then
    [[ -x "node_modules/.bin/tsx" ]] || fail "Node ${NODE_VERSION:-$(node --version)} cannot strip TypeScript and local node_modules/.bin/tsx is missing."
  fi
}

run_bootstrap_admin() {
  log "Bootstrapping production admin user"
  cd "${APP_DIR}"
  if node -e "const [major, minor] = process.versions.node.split('.').map(Number); process.exit(major > 22 || (major === 22 && minor >= 6) ? 0 : 1)"; then
    run_app node --experimental-strip-types scripts/bootstrap-admin.ts
  else
    run_app node_modules/.bin/tsx scripts/bootstrap-admin.ts
  fi
}

run_auth_verification() {
  log "Verifying and repairing bootstrap authentication state"
  cd "${APP_DIR}"
  local mode="${1:-runtime}"
  export AUTH_VERIFY_TENANT_ID="${AUTH_VERIFY_TENANT_ID:-${BOOTSTRAP_TENANT_ID}}"
  export AUTH_VERIFY_BRANCH_ID="${AUTH_VERIFY_BRANCH_ID:-${BOOTSTRAP_BRANCH_ID}}"
  export AUTH_VERIFY_USERNAME="${AUTH_VERIFY_USERNAME:-${BOOTSTRAP_ADMIN_USERNAME}}"
  export AUTH_VERIFY_PASSWORD="${AUTH_VERIFY_PASSWORD:-${BOOTSTRAP_ADMIN_PASSWORD}}"
  if [[ "${mode}" == "db-only" ]]; then
    export AUTH_VERIFY_SKIP_RUNTIME=1
  else
    unset AUTH_VERIFY_SKIP_RUNTIME
    export AUTH_VERIFY_BASE_URL="${AUTH_VERIFY_BASE_URL:-http://127.0.0.1:${ROOT_PORT}}"
  fi
  if node -e "const [major, minor] = process.versions.node.split('.').map(Number); process.exit(major > 22 || (major === 22 && minor >= 6) ? 0 : 1)"; then
    run_app node --experimental-strip-types scripts/verify-auth.ts
  else
    run_app node_modules/.bin/tsx scripts/verify-auth.ts
  fi
}

validate_ecosystem() {
  log "Validating canonical PM2 ecosystem"
  cd "${APP_DIR}"
  node - <<'NODE'
const ecosystem = require('./ecosystem.config.cjs');
const apps = Array.isArray(ecosystem.apps) ? ecosystem.apps : [];
const names = apps.map((app) => app.name).sort().join(',');
if (names !== 'adisyum-root-app,adisyum-website') {
  throw new Error(`Invalid PM2 apps: ${names}`);
}
const root = apps.find((app) => app.name === 'adisyum-root-app');
const website = apps.find((app) => app.name === 'adisyum-website');
if (!String(root?.args || '').includes('-p 3000')) throw new Error('adisyum-root-app must start on port 3000');
if (!String(website?.args || '').includes('-p 3010')) throw new Error('adisyum-website must start on port 3010');
if (apps.some((app) => /pos|system-admin/i.test(app.name) && !['adisyum-root-app', 'adisyum-website'].includes(app.name))) {
  throw new Error('Forbidden old PM2 app name found');
}
console.log('ecosystem OK:', names);
NODE
}

rebuild_prisma_and_typecheck() {
  log "Regenerating Prisma Client and validating TypeScript"
  cd "${APP_DIR}"
  run_app npx prisma validate
  run_app npx prisma generate
  run_app npx prisma db push
  run_bootstrap_admin
  run_auth_verification db-only
  run_app npx tsc --noEmit
}

build_apps() {
  log "Building root app and website from clean artifacts"
  cd "${APP_DIR}"
  run_app node node_modules/next/dist/bin/next build
  [[ -s ".next/BUILD_ID" ]] || fail "Root .next/BUILD_ID missing"
  [[ -d ".next/server" ]] || fail "Root .next/server missing"
  [[ -d ".next/static" ]] || fail "Root .next/static missing"
  [[ -d ".next/server/app/app" || -f ".next/server/app/app.html" || -f ".next/server/app/app/page.js" ]] || fail "Root /app build artifact missing"
  [[ -d ".next/server/app/system-admin" || -f ".next/server/app/system-admin.html" || -f ".next/server/app/system-admin/page.js" ]] || fail "Root /system-admin build artifact missing"
  log "Root BUILD_ID=$(cat .next/BUILD_ID)"

  run_app npm --prefix apps/website run build
  [[ -s "apps/website/.next/BUILD_ID" ]] || fail "Website .next/BUILD_ID missing"
  [[ -d "apps/website/.next/server" ]] || fail "Website .next/server missing"
  [[ -d "apps/website/.next/static" ]] || fail "Website .next/static missing"
  log "Website BUILD_ID=$(cat apps/website/.next/BUILD_ID)"
}

start_pm2_clean() {
  log "Starting canonical PM2 apps"
  cd "${APP_DIR}"
  run_app pm2 start ecosystem.config.cjs --update-env
  sleep 8
  validate_pm2
  run_app pm2 save
}

validate_pm2() {
  log "Validating PM2 exact app set and restart stability"
  local names
  names="$(pm2 jlist | node -e "let s=''; process.stdin.on('data',d=>s+=d); process.stdin.on('end',()=>{const apps=JSON.parse(s||'[]'); const names=apps.map(a=>a.name).sort(); console.log(names.join(',')); if(apps.length!==2) process.exit(2); if(names.join(',')!=='adisyum-root-app,adisyum-website') process.exit(3); if(names.includes('adisyum-pos-app')||names.includes('adisyum-system-admin')) process.exit(4); if(apps.some(a=>a.pm2_env.status!=='online')) process.exit(5); if(apps.some(a=>Number(a.pm2_env.restart_time||0)>2||Number(a.pm2_env.unstable_restarts||0)>0)) process.exit(6);})")"
  [[ "${names}" == "adisyum-root-app,adisyum-website" ]] || fail "Unexpected PM2 state: ${names}"
  pm2 list
}

write_nginx() {
  log "Reconstructing canonical NGINX config"
  mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled /etc/nginx/conf.d

  cat >/etc/nginx/conf.d/adisyum-websocket-map.conf <<'MAP'
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
MAP

  cat >/etc/nginx/sites-available/adisyum.conf <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 50M;

    location ^~ ${ROOT_ASSET_PREFIX}/_next/ {
        rewrite ^${ROOT_ASSET_PREFIX}(/_next/.*)\$ \$1 break;
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /app {
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /app/ {
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /system-admin {
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /system-admin/ {
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ~ ^/(api|adisyonsistemi|access|dashboard|pos|orders|products|warehouse|reports|finance|settings|branches|delivery|developer|bar-control|floor|integrations|kds|overview|qr|qr-menu|saas)(/|\$) {
        proxy_pass http://127.0.0.1:${ROOT_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:${WEBSITE_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

  rm -f /etc/nginx/sites-enabled/default
  rm -f /etc/nginx/sites-enabled/app.conf /etc/nginx/sites-enabled/admin.conf /etc/nginx/sites-enabled/website.conf
  rm -f /etc/nginx/sites-available/app.conf /etc/nginx/sites-available/admin.conf /etc/nginx/sites-available/website.conf
  ln -sfn /etc/nginx/sites-available/adisyum.conf /etc/nginx/sites-enabled/adisyum.conf
}

validate_nginx() {
  log "Validating NGINX config and routing drift"
  nginx -t
  nginx -T > "${BACKUP_DIR}/nginx/nginx-T.after.txt" 2>&1

  if grep -Eq "server_name[[:space:]]+(app|admin)\\.${DOMAIN}" "${BACKUP_DIR}/nginx/nginx-T.after.txt"; then
    fail "Stale app/admin subdomain NGINX server block is active"
  fi
  if grep -Eq "proxy_pass[[:space:]]+http://127\\.0\\.0\\.1:3020" "${BACKUP_DIR}/nginx/nginx-T.after.txt"; then
    fail "Stale 3020 NGINX upstream is active"
  fi
  grep -Eq "location[[:space:]]+=[[:space:]]+/app" "${BACKUP_DIR}/nginx/nginx-T.after.txt" || fail "Missing location = /app"
  grep -Eq "location[[:space:]]+\\^~[[:space:]]+/app/" "${BACKUP_DIR}/nginx/nginx-T.after.txt" || fail "Missing location ^~ /app/"
  grep -Eq "location[[:space:]]+=[[:space:]]+/system-admin" "${BACKUP_DIR}/nginx/nginx-T.after.txt" || fail "Missing location = /system-admin"
  grep -Eq "location[[:space:]]+\\^~[[:space:]]+/system-admin/" "${BACKUP_DIR}/nginx/nginx-T.after.txt" || fail "Missing location ^~ /system-admin/"

  systemctl reload nginx
}

is_healthy_http_status() {
  local code="$1"
  case "${code}" in
    200|201|204|301|302|303|307|308) return 0 ;;
    *) return 1 ;;
  esac
}

wait_for_healthy_route() {
  local url="$1"
  local code="" final_code="" final_url=""
  for _ in $(seq 1 45); do
    code="$(curl -ksS -o /dev/null -w '%{http_code}' --max-time 8 "${url}" || true)"
    if is_healthy_http_status "${code}"; then
      final_code="$(curl -kLsS -o /dev/null -w '%{http_code}' --max-time 15 "${url}" || true)"
      final_url="$(curl -kLsS -o /dev/null -w '%{url_effective}' --max-time 15 "${url}" || true)"

      if [[ "${code}" =~ ^30[12378]$ ]]; then
        if is_healthy_http_status "${final_code}"; then
          log "${url} HTTP ${code}; redirect target healthy (${final_code}) ${final_url}"
          return 0
        fi
      else
        log "${url} HTTP ${code}"
        return 0
      fi
    fi
    sleep 2
  done
  fail "${url} expected healthy HTTP 2xx/3xx, got initial=${code:-none} final=${final_code:-none} final_url=${final_url:-unknown}"
}

validate_runtime_routes() {
  log "Validating local and public runtime routes"
  if ss -ltnp | grep -q ':3020'; then
    ss -ltnp | grep ':3020' || true
    fail "Port 3020 is listening"
  fi

  wait_for_healthy_route "http://127.0.0.1:${ROOT_PORT}"
  wait_for_healthy_route "http://127.0.0.1:${ROOT_PORT}/app"
  wait_for_healthy_route "http://127.0.0.1:${ROOT_PORT}/system-admin"
  wait_for_healthy_route "http://127.0.0.1:${WEBSITE_PORT}"

  wait_for_healthy_route "https://${DOMAIN}"
  wait_for_healthy_route "https://${DOMAIN}/app"
  wait_for_healthy_route "https://${DOMAIN}/system-admin"
}

print_final_state() {
  cat <<EOF

Clean VPS reconstruction completed.

Root cause:
- VPS runtime/deployment state drifted from source truth: stale PM2 dump/processes, stale NGINX routes, stale build artifacts, stale dependency/generated outputs, and old split-domain/runtime assumptions.

Preserved:
- Current source code in ${APP_DIR}
- .env files
- Database
- uploads/assets

Rebuilt:
- node_modules
- Prisma Client
- .next build artifacts
- PM2 state
- NGINX routing
- runtime processes

Canonical filesystem layout:
- ${APP_DIR}/app                 root Next.js app routes
- ${APP_DIR}/apps/website        website Next.js app
- ${APP_DIR}/.next               root production build
- ${APP_DIR}/apps/website/.next  website production build
- ${APP_DIR}/ecosystem.config.cjs canonical two-app PM2 config

Final PM2 apps:
- adisyum-root-app   -> 127.0.0.1:${ROOT_PORT}
- adisyum-website    -> 127.0.0.1:${WEBSITE_PORT}

Final NGINX map:
- https://${DOMAIN}              -> http://127.0.0.1:${WEBSITE_PORT}
- https://${DOMAIN}/app          -> http://127.0.0.1:${ROOT_PORT}/app
- https://${DOMAIN}/system-admin -> http://127.0.0.1:${ROOT_PORT}/system-admin

Build IDs:
- Root: $(cat "${APP_DIR}/.next/BUILD_ID")
- Website: $(cat "${APP_DIR}/apps/website/.next/BUILD_ID")

Backup:
- ${BACKUP_DIR}

Log:
- ${LOG_FILE}
EOF
}

main() {
  require_root
  require_command openssl
  require_command node
  require_command npm
  require_command npx
  require_command pm2
  require_command nginx
  require_command curl
  require_command grep
  require_command getent
  require_command ss
  require_command systemctl
  require_layout
  recover_or_create_env

  backup_preserved_state
  inspect_drift_before_cleanup
  load_env
  stop_all_runtime
  clean_pm2_state
  clean_filesystem_runtime
  install_dependencies
  validate_node_runtime
  validate_ecosystem
  rebuild_prisma_and_typecheck
  build_apps
  start_pm2_clean
  run_auth_verification
  write_nginx
  validate_nginx
  validate_runtime_routes
  print_final_state
}

main "$@"
